### ISSUE TITLE
[FR] Quality preferences

### ISSUE THREAD

**Issue by ildar** [theScrabi/NewPipe#15] opened 2015-09-13 16:26 UTC
It would be great to have the Video Quality in Settings.

I know that different videos may have different qualities available, so the feature may be non-trivial to implement. Then let's discuss it here if you think it's appropriate.

**Comment by fred702** [comment] 2015-09-13 17:52
possible duplicate of #9

**Comment by ildar** [comment] 2015-09-13 18:05
​sure

**Closed** 2015-09-13 18:06 UTC
