### ISSUE TITLE
select user

### ISSUE THREAD

**Issue by Spamiad** [theScrabi/NewPipe#358] opened 2016-09-25 00:51 UTC
Great app...please keeping going.

Miss they functionality of being able to access users and their uploads

**Comment by icasdri** [comment] 2016-09-25 03:21
Duplicate of #2?

**Comment by theScrabi** [comment] 2016-09-25 07:50
Will come with rhe next version... At least you can see the users conted, but so far you can't search for a user.

**Closed** 2016-09-25 07:50 UTC
