### ISSUE TITLE
App malfunctions when trying to play video, audio or download

### ISSUE THREAD

**Issue by chin123** [theScrabi/NewPipe#81] opened 2015-11-12 07:14 UTC
This is tested on android 4.4.2 and 5.1.1:
When trying to do anything related to the video this is what happens:  
When trying to view the video, or pressing the download button the error "unfortunately newpipe has stopped" appears and   the app reloads to the previous screen( the search screen).  
When trying to play audio, it asks me to install a stream player but i already have vlc.  
Steps to reproduce:  
1. Search for any video.  
2. Try and play the video, audio or press the download button.  
3. One of the errors i described above will happen.  
I know its not a problem with my network because visiting youtube from the browser works and i can play videos. I have also tried reinstalling. This is with the default settings on newpipe and i am running the latest version. Unfortunately i cannot provide the log because i dont have root.

**Comment by chschtsch** [comment] 2015-11-12 08:47
Interestingly enough that I had the same errors (including not recognizing already installed VLC) on my 4.2.2 while testing latest versions pulled from master and built on my computer. But later it got working good again. I don't remember the reason why it gave such errors or the commit when it happend. But it was nightly build, not the release from F-Droid (which I never had problem with), so I though it's not a big deal.

I think, a new 0.6.0 release is on its way, so you can just wait for it to appear in the store.
Or you can pull the project from GitHub and build it with Android Studio.

**Comment by theScrabi** [comment] 2015-11-12 09:36
It will not solve that problem. I know about it, and I know where it happens. But I don't know what happens. Therefore I’ve put a stack trace at position where the error occurs, and i know that there is something thrown (otherwise the install vlc dialogue would not come up).

@chin123: Since I was not able to reproduce that error. Someone needs to provide a log of the error.

**Comment by ata2001** [comment] 2015-11-12 11:55
11-12 09:10:48.351 I/Timeline(1580): Timeline: Activity_windows_visible id: ActivityRecord{41d49a40 u0 org.schabi.newpipe/.VideoItemDetailActivity t80} time:133437766
11-12 09:10:48.538 I/Timeline(17339): Timeline: Activity_idle id: android.os.BinderProxy@41ba40b0 time:133437955
11-12 09:10:49.843 D/AudioHardwareMot(1167): AudioStreamOutMot::standby called
11-12 09:10:49.843 D/AudioHardwareMot(1167): Output 0x2a00d020 entering standby
11-12 09:10:49.851 D/AudioHardwareMot(1167): Closing Output device
11-12 09:10:53.483 W/System.err(17339): java.lang.IllegalStateException: No successful match so far
11-12 09:10:53.562 W/System.err(17339): 	at java.util.regex.Matcher.ensureMatch(Matcher.java:596)
11-12 09:10:53.562 W/System.err(17339): 	at java.util.regex.Matcher.group(Matcher.java:357)
11-12 09:10:53.562 W/System.err(17339): 	at org.schabi.newpipe.youtube.YoutubeExtractor.loadDecryptionCode(YoutubeExtractor.java:464)
11-12 09:10:53.562 W/System.err(17339): 	at org.schabi.newpipe.youtube.YoutubeExtractor.getVideoInfo(YoutubeExtractor.java:193)
11-12 09:10:53.562 W/System.err(17339): 	at org.schabi.newpipe.VideoItemDetailFragment$ExtractorRunnable.run(VideoItemDetailFragment.java:92)
11-12 09:10:53.562 W/System.err(17339): 	at java.lang.Thread.run(Thread.java:841)
11-12 09:10:53.827 W/System.err(17339): org.mozilla.javascript.EcmaError: ReferenceError: "Zq" is not defined. (decryptionCode#1)
11-12 09:10:53.827 W/System.err(17339): 	at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:3951)
11-12 09:10:53.827 W/System.err(17339): 	at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:3929)
11-12 09:10:53.835 W/System.err(17339): 	at org.mozilla.javascript.ScriptRuntime.notFoundError(ScriptRuntime.java:4019)
11-12 09:10:53.835 W/System.err(17339): 	at org.mozilla.javascript.ScriptRuntime.getNameFunctionAndThis(ScriptRuntime.java:2314)
11-12 09:10:53.835 W/System.err(17339): 	at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1313)
11-12 09:10:53.835 W/System.err(17339): 	at script.decrypt(decryptionCode:1)
11-12 09:10:53.835 W/System.err(17339): 	at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:815)
11-12 09:10:53.835 W/System.err(17339): 	at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:109)
11-12 09:10:53.835 W/System.err(17339): 	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:393)
11-12 09:10:53.835 W/System.err(17339): 	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3282)
11-12 09:10:53.835 W/System.err(17339): 	at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:107)
11-12 09:10:53.835 W/System.err(17339): 	at org.schabi.newpipe.youtube.YoutubeExtractor.decryptSignature(YoutubeExtractor.java:495)
11-12 09:10:53.835 W/System.err(17339): 	at org.schabi.newpipe.youtube.YoutubeExtractor.parseDashManifest(YoutubeExtractor.java:337)
11-12 09:10:53.835 W/System.err(17339): 	at org.schabi.newpipe.youtube.YoutubeExtractor.getVideoInfo(YoutubeExtractor.java:199)
11-12 09:10:53.835 W/System.err(17339): 	at org.schabi.newpipe.VideoItemDetailFragment$ExtractorRunnable.run(VideoItemDetailFragment.java:92)
11-12 09:10:53.835 W/System.err(17339): 	at java.lang.Thread.run(Thread.java:841)
11-12 09:10:53.843 E/class org.schabi.newpipe.youtube.YoutubeExtractor(17339): Dash manifest seems not to bee available.
11-12 09:10:53.843 W/System.err(17339): java.lang.NullPointerException
11-12 09:10:53.843 W/System.err(17339): 	at org.schabi.newpipe.youtube.YoutubeExtractor.decryptSignature(YoutubeExtractor.java:500)
11-12 09:10:53.851 W/System.err(17339): 	at org.schabi.newpipe.youtube.YoutubeExtractor.parseDashManifest(YoutubeExtractor.java:337)
11-12 09:10:53.851 W/System.err(17339): 	at org.schabi.newpipe.youtube.YoutubeExtractor.getVideoInfo(YoutubeExtractor.java:199)
11-12 09:10:53.851 W/System.err(17339): 	at org.schabi.newpipe.VideoItemDetailFragment$ExtractorRunnable.run(VideoItemDetailFragment.java:92)
11-12 09:10:53.851 W/System.err(17339): 	at java.lang.Thread.run(Thread.java:841)
11-12 09:10:53.937 W/System.err(17339): org.mozilla.javascript.EcmaError: ReferenceError: "Zq" is not defined. (decryptionCode#1)
11-12 09:10:53.937 W/System.err(17339): 	at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:3951)
11-12 09:10:53.944 W/System.err(17339): 	at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:3929)
11-12 09:10:53.944 W/System.err(17339): 	at org.mozilla.javascript.ScriptRuntime.notFoundError(ScriptRuntime.java:4019)
11-12 09:10:53.944 W/System.err(17339): 	at org.mozilla.javascript.ScriptRuntime.getNameFunctionAndThis(ScriptRuntime.java:2314)
11-12 09:10:53.944 W/System.err(17339): 	at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1313)
11-12 09:10:53.944 W/System.err(17339): 	at script.decrypt(decryptionCode:1)
11-12 09:10:53.944 W/System.err(17339): 	at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:815)
11-12 09:10:53.944 W/System.err(17339): 	at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:109)
11-12 09:10:53.944 W/System.err(17339): 	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:393)
11-12 09:10:53.944 W/System.err(17339): 	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3282)
11-12 09:10:53.944 W/System.err(17339): 	at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:107)
11-12 09:10:53.944 W/System.err(17339): 	at org.schabi.newpipe.youtube.YoutubeExtractor.decryptSignature(YoutubeExtractor.java:495)
11-12 09:10:53.944 W/System.err(17339): 	at org.schabi.newpipe.youtube.YoutubeExtractor.getVideoInfo(YoutubeExtractor.java:226)
11-12 09:10:53.944 W/System.err(17339): 	at org.schabi.newpipe.VideoItemDetailFragment$ExtractorRunnable.run(VideoItemDetailFragment.java:92)
11-12 09:10:53.944 W/System.err(17339): 	at java.lang.Thread.run(Thread.java:841)
11-12 09:10:53.944 W/System.err(17339): java.lang.NullPointerException
11-12 09:10:53.944 W/System.err(17339): 	at org.schabi.newpipe.youtube.YoutubeExtractor.decryptSignature(YoutubeExtractor.java:500)
11-12 09:10:53.944 W/System.err(17339): 	at org.schabi.newpipe.youtube.YoutubeExtractor.getVideoInfo(YoutubeExtractor.java:226)
11-12 09:10:53.944 W/System.err(17339): 	at org.schabi.newpipe.VideoItemDetailFragment$ExtractorRunnable.run(VideoItemDetailFragment.java:92)
11-12 09:10:53.944 W/System.err(17339): 	at java.lang.Thread.run(Thread.java:841)
11-12 09:10:54.132 I/dalvikvm(17339): Jit: resizing JitTable from 4096 to 8192
11-12 09:10:54.280 I/ActivityManager(1580): Process com.android.packageinstaller (pid 17007) has died.
11-12 09:10:54.952 W/class org.schabi.newpipe.VideoItemDetailFragment(17339): updateInfo(): Fragment closed before thread ended work... or else
11-12 09:10:54.952 W/System.err(17339): java.lang.NullPointerException
11-12 09:10:54.952 W/System.err(17339): 	at org.schabi.newpipe.VideoItemDetailFragment.updateInfo(VideoItemDetailFragment.java:224)
11-12 09:10:54.952 W/System.err(17339): 	at org.schabi.newpipe.VideoItemDetailFragment$VideoResultReturnedRunnable.run(VideoItemDetailFragment.java:127

I dunno it helps or not, but i reproduced the problem, with a video i can't play.

**Comment by theScrabi** [comment] 2015-11-13 00:20
Ok i thought about something else. But i think i might know the error now. If i'm getting it right, this error is already fixed. The next version 0.6.0 will be shipped in a few days.

**Closed by theScrabi** 2015-11-13 00:20 UTC
Labels: bug
