### ISSUE TITLE
Improve background music playback

### ISSUE THREAD

**Issue by devnoname120** [theScrabi/NewPipe#267] opened 2016-04-13 23:34 UTC
There are a few issues / possible improvements with this feature:

- When clicking on background playback, a notification appears, but nothing in the app. It would be nice to be able to see the progress, go forward, etc. For example, a small bar at the bottom could be added, similar to most music players.
- When clicking on background playback while another video is playing as a music in the background, nothing happens. Instead, it should stop the current music, and play the new one.

Thank you for this app!

**Comment by Dostoi** [comment] 2016-04-14 09:19
Duplicate of #158 for the second part

**Closed** 2016-04-17 13:44 UTC
